INSERT INTO insect (
    name_insect, 
    species, 
    description, 
    kingdom, 
    phylum, 
    class, 
    order_insect, 
    family, 
    described_by, 
    year_described, 
    activity, 
    cycle, 
    image
) VALUES 
("Fourmi rousse", "Formica rufa", "Fourmi des bois, connue pour ses nids de feuilles.", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Formicidae", "Linnaeus", "1761-01-01", "Diurne", "Métamorphose complète", "null"),
("Cybister tricolore", "Cybister tripunctatus", "Un grand coléoptère aquatique avec une coloration vive.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Dytiscidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Abeille domestique", "Apis mellifera", "Abeille domestique, pollinisateur essentiel.", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouche du vinaigre", "Drosophila melanogaster", "Mouche du vinaigre, utilisée en génétique.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Drosophilidae", "Meigen", "1830-01-01", "Diurne", "Métamorphose complète", "null"),
("Coléoptère des bois", "Carabus nemoralis", "Coléoptère nocturne, corps allongé et brillant.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Carabidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Papillon machaon", "Papilio machaon", "Papillon très coloré, connu pour ses grandes ailes.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Papilionidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Ver de farine", "Tenebrio molitor", "Vers de farine, insecte comestible en élevage.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Tenebrionidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Mouche des fruits", "Ceratitis capitata", "Mouche des fruits, nuisible aux cultures.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Tephritidae", "Wiedemann", "1824-01-01", "Diurne", "Métamorphose complète", "null"),
("Grillon des champs", "Gryllus campestris", "Grillon des champs, connu pour son chant.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Gryllidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose incomplète", "null"),
("Sauterelle migratrice", "Locusta migratoria", "Sauterelle migratrice, connue pour ses essaims.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Cigale des arbres", "Cicada", "Cigale connue pour son chant puissant.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Cicadidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Punaise des bois", "Pentatoma rufipes", "Punaise à pattes rouges, fréquente dans les forêts.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Pentatomidae", "Linnaeus", "1763-01-01", "Diurne", "Métamorphose complète", "null"),
("Mante religieuse", "Mantis religiosa", "Insecte prédateur, connu pour sa posture caractéristique.", "Animalia", "Arthropoda", "Insecta", "Mantodea", "Mantidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Chenille processionnaire", "Thaumetopea pityocampa", "Chenille connue pour ses procession dans les pins.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Notodontidae", "Schiff", "1834-01-01", "Diurne", "Métamorphose complète", "null"),
("Cicadelle", "Empoasca", "Petit insecte suceur, souvent présent dans les cultures.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Cicadellidae", "Latreille", "1802-01-01", "Diurne", "Métamorphose complète", "null"),
("Moucheron", "Culicoides", "Petit insecte volant, souvent porteur de maladies.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Ceratopogonidae", "Latreille", "1802-01-01", "Nocturne", "Métamorphose complète", "null"),
("Punaise des céréales", "Sitobion avenae", "Insecte suceur fréquent dans les cultures de blé.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Aphididae", "Fabr.", "1775-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle verte", "Omocestus viridulus", "Sauterelle fréquente dans les prairies humides.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Diptère", "Musca domestica", "Mouche domestique, fréquente dans les habitations.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Muscidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Scarabée", "Scarabaeidae", "Coléoptère connu pour sa forme ronde et sa couleur.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Scarabaeidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Syrphe", "Syrphidae", "Insecte ressemblant à une abeille, excellent pollinisateur.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Pavillon de la couronne", "Eristalis tenax", "Insecte souvent vu sur les fleurs, forme de mouche.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Noctuelle", "Noctuidae", "Papillon nocturne, souvent nuisible aux cultures.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Noctuidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Moucheron de nuit", "Culex pipiens", "Insecte piquant, connu pour être actif la nuit.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Culicidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Chenille de la chrysomèle", "Chrysomela", "Chenille fréquente dans les cultures de légumes.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Chrysomelidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Moucheron de jardin", "Phytomyza", "Petit insecte suceur, nuisible pour les plantes.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Agromyzidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Libellule", "Anisoptera", "Insecte aquatique aux ailes transparentes, bon prédateur.", "Animalia", "Arthropoda", "Insecta", "Odonata", "Libellulidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sphinx du tabac", "Manduca sexta", "Papillon nocturne, connu pour son vol rapide.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Sphingidae", "Linnaeus", "1763-01-01", "Nocturne", "Métamorphose complète", "null"),
("Mouche de l""olive", "Bactrocera oleae", "Insecte nuisible pour les oliviers.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Tephritidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mante d""eau", "Lestes", "Insecte aquatique avec une couleur éclatante.", "Animalia", "Arthropoda", "Insecta", "Odonata", "Lestidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Papillon de nuit", "Noctuidae", "Papillon qui vole principalement la nuit.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Noctuidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Chrysomèle", "Chrysomelidae", "Coléoptère connu pour ses couleurs vives.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Chrysomelidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle brune", "Gampsocleis", "Insecte vert qui chante dans les champs.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Tettigoniidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Pyrale", "Pyralidae", "Papillon dont les larves se nourrissent des grains.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Pyralidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Moucheron de jardin", "Syrphidae", "Insecte pollinisateur ressemblant à une abeille.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null");
("Criquet des champs", "Chorthippus parallelus", "Insecte sauteur, connu pour son chant.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Mouche à miel", "Eristalis tenax", "Insecte pollinisateur souvent vu sur les fleurs.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Cicadelle des prairies", "Oncometopia alpha", "Petit insecte suceur, souvent présent dans les prairies.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Cicadellidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle de montagne", "Chrysochraon", "Insecte sauteur qui vit en altitude.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Coléoptère de jardin", "Harmonia axyridis", "Coléoptère aux couleurs vives, prédateur de pucerons.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Coccinellidae", "Pallas", "1773-01-01", "Diurne", "Métamorphose complète", "null"),
("Mante du ciel", "Stagmomantis", "Insecte prédateur avec de grandes ailes.", "Animalia", "Arthropoda", "Insecta", "Mantodea", "Mantidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Mouche de sable", "Phlebotomus", "Insecte piqueur, souvent porteur de maladies.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Psychodidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Ver de soie", "Bombyx mori", "Insecte dont la larve produit de la soie.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Bombycidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sphinx colibri", "Macroglossum stellatarum", "Papillon nocturne, connu pour son vol stationnaire.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Sphingidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Moustique", "Culex", "Insecte piqueur, souvent responsable de maladies.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Culicidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Punaise des cactées", "Tropidothorax", "Insecte nuisible pour les plantes succulentes.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Miridae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Criquet à ailes courtes", "Gampsocleis glabra", "Insecte sauteur aux ailes peu développées.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Tettigoniidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Pavillon des fleurs", "Eristalis", "Insecte pollinisateur souvent vu sur les fleurs.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Cigale de la forêt", "Cicadidae", "Cigale connue pour son chant fort dans les forêts.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Cicadidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle des prairies", "Chorthippus", "Insecte sauteur vivant dans les prairies.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Cicadelle des cultures", "Empoasca fabae", "Insecte suceur présent dans les cultures.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Cicadellidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouche des espaces verts", "Lucilia sericata", "Mouche souvent trouvée dans les jardins.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Calliphoridae", "Meigen", "1826-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle des rivières", "Pseudopomala", "Insecte aquatique, bon nageur.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Papillon des jardins", "Danaus plexippus", "Papillon migrateur connu pour ses couleurs vives.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Nymphalidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouche de fleur", "Anthrax", "Mouche qui se nourrit de nectar, semblable à une abeille.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Bombyliidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouette de jardin", "Cheilosia", "Insecte pollinisateur souvent trouvé dans les jardins.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Punaise de l'aubépine", "Acanthosoma", "Insecte phytophage sur les aubépines.", "Animalia", "Arthropoda", "Insecta", "Hemiptera", "Pentatomidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Criquet des sous-bois", "Phaneroptera", "Insecte qui vit dans les endroits ombragés.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Tettigoniidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Mouche du tabac", "Myiopsis", "Insecte nuisible dans les cultures de tabac.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Grillon des arbres", "Oecanthus", "Insecte chanteur des forêts.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Gryllidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Papillon de la reine", "Danaus", "Papillon connu pour sa migration impressionnante.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Nymphalidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouche du vinaigre", "Drosophila", "Mouche utilisée en génétique, attirée par les fruits.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Drosophilidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle des roses", "Acrida", "Insecte des jardins, aimé pour sa couleur.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Acrididae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Coléoptère des ordures", "Scarabaeus", "Insecte connu pour son rôle dans la décomposition.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Scarabaeidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mante d'eau", "Lestes", "Insecte aquatique avec une couleur éclatante.", "Animalia", "Arthropoda", "Insecta", "Odonata", "Lestidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Mouche de l'olive", "Bactrocera oleae", "Insecte nuisible pour les oliviers.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Tephritidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Papillon de nuit", "Noctuidae", "Papillon qui vole principalement la nuit.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Noctuidae", "Linnaeus", "1758-01-01", "Nocturne", "Métamorphose complète", "null"),
("Chrysomèle", "Chrysomelidae", "Coléoptère connu pour ses couleurs vives.", "Animalia", "Arthropoda", "Insecta", "Coleoptera", "Chrysomelidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Sauterelle brune", "Gampsocleis", "Insecte vert qui chante dans les champs.", "Animalia", "Arthropoda", "Insecta", "Orthoptera", "Tettigoniidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose incomplète", "null"),
("Pyrale", "Pyralidae", "Papillon dont les larves se nourrissent des grains.", "Animalia", "Arthropoda", "Insecta", "Lepidoptera", "Pyralidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null"),
("Moucheron de jardin", "Syrphidae", "Insecte pollinisateur ressemblant à une abeille.", "Animalia", "Arthropoda", "Insecta", "Diptera", "Syrphidae", "Linnaeus", "1758-01-01", "Diurne", "Métamorphose complète", "null");
